export enum OrderStatus {
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PROCESSING = 'PROCESSING',
  PREPARING = 'PREPARING',
  SHIPPED = 'SHIPPED',
  CANCELED = 'CANCELED',
}
