export enum ShippingTypes {
  // CORREIOS
  CORREIOS_CARTA_REGISTRADA = 'CORREIOS_CARTA_REGISTRADA',
  CORREIOS_PAC = 'CORREIOS_PAC',
  CORREIOS_SEDEX = 'CORREIOS_SEDEX',
  CORREIOS_SEDEX_10 = 'CORREIOS_SEDEX_10',
  CORREIOS_SEDEX_HOJE = 'CORREIOS_SEDEX_HOJE',
}
