export enum EmailTypes {
  // ORDERS
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_PAYED = 'ORDER_PAYED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_PAYMENT_REMINDER = 'ORDER_PAYMENT_REMINDER',
  // PRODUCTS - CRON
  PRODUCT_AVAILABLE = 'PRODUCT_AVAILABLE',
  // ERRORS - CRON
  NEW_ERRORS = 'NEW_ERRORS',
  // WARNINGS - CRON
  ORDER_PAYMENT_VALUE_CONFLICT = 'ORDER_PAYMENT_VALUE_CONFLICT',
}
// TODO - NF EMITIDA?
