export enum MailTypes {
  // ORDERS
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_UPDATE = 'ORDER_UPDATE',
  // PAYMENTS
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  // PRODUCTS
  PRODUCT_AVAILABLE = 'PRODUCT_AVAILABLE',
  // ERRORS
  NEW_ERRORS = 'NEW_ERRORS',
  // WARNINGS
  ORDER_PAYMENT_VALUE_CONFLICT = 'ORDER_PAYMENT_VALUE_CONFLICT',
}
// TODO - NF EMITIDA?
